[mypy]
explicit_package_bases = True
ignore_missing_imports = True

[mypy-tests.*]
ignore_errors = True

[mypy-config.*]
ignore_errors = True

[mypy-main.models.*]
ignore_errors = True

[mypy-main.app.prometheus.chat]
ignore_errors = True

[mypy-main.controller.*]
ignore_errors = True

[mypy-main.app.authentication.*]
ignore_errors = True