"""Initial migration

Revision ID: 25af7ad931e7
Revises:
Create Date: 2026-04-03 11:51:52.506814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25af7ad931e7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("userId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("passwordHash", sa.Text(), nullable=True),
        sa.Column("googleId", sa.String(length=255), nullable=True),
        sa.Column("roles", sa.Text(), nullable=True),
        sa.Column("createdAt", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("userId"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_googleId"), "users", ["googleId"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "prometheus",
        sa.Column("sessionId", sa.String(length=255), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("history", sa.JSON(), nullable=True),
        sa.Column("lastActivity", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.Column("createdAt", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["users.userId"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sessionId"),
    )
    op.create_table(
        "stocksapi_keys",
        sa.Column("apiKey", sa.String(length=255), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("requestLimit", sa.Integer(), nullable=False),
        sa.Column("currentUsage", sa.Integer(), nullable=False),
        sa.Column("lastReset", sa.TIMESTAMP(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["users.userId"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("apiKey"),
    )
    op.create_index(op.f("ix_stocksapi_keys_userId"), "stocksapi_keys", ["userId"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocksapi_keys_userId"), table_name="stocksapi_keys")
    op.drop_table("stocksapi_keys")
    op.drop_table("prometheus")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_googleId"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
