"""wallet tables

Revision ID: 73211a401c34
Revises: f7a8b9c0d1e2
Create Date: 2026-09-30 20:38:20.280169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73211a401c34"
down_revision: Union[str, Sequence[str], None] = "f7a8b9c0d1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("walletId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("lastRecalc", sa.TIMESTAMP(), nullable=True),
        sa.Column("createdAt", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["users.userId"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("walletId"),
    )
    op.create_index(op.f("ix_wallets_userId"), "wallets", ["userId"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("holdingId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("walletId", sa.Integer(), nullable=False),
        sa.Column("assetType", sa.String(length=20), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("tickerName", sa.String(length=120), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("avgPrice", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("percentIdeal", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("updatedAt", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["walletId"], ["wallets.walletId"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("holdingId"),
        sa.UniqueConstraint("walletId", "ticker", name="uq_holdings_wallet_ticker"),
    )
    op.create_index(op.f("ix_holdings_ticker"), "holdings", ["ticker"], unique=False)
    op.create_index(op.f("ix_holdings_walletId"), "holdings", ["walletId"], unique=False)
    op.create_table(
        "snapshots",
        sa.Column("snapshotId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("walletId", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("applied", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("equity", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("variation", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("profitTwr", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("profitAmount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("profitTwr12m", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("profitTwr12mAmount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["walletId"], ["wallets.walletId"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("snapshotId"),
        sa.UniqueConstraint("walletId", "date", name="uq_snapshots_wallet_date"),
    )
    op.create_index(op.f("ix_snapshots_date"), "snapshots", ["date"], unique=False)
    op.create_index(op.f("ix_snapshots_walletId"), "snapshots", ["walletId"], unique=False)
    op.create_table(
        "targets",
        sa.Column("targetId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("walletId", sa.Integer(), nullable=False),
        sa.Column("keyKind", sa.Enum("ticker", "group", name="target_key_kind"), nullable=False),
        sa.Column("keyValue", sa.String(length=40), nullable=False),
        sa.Column("percentIdeal", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["walletId"], ["wallets.walletId"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("targetId"),
        sa.UniqueConstraint("walletId", "keyKind", "keyValue", name="uq_targets_wallet_key"),
    )
    op.create_index(op.f("ix_targets_walletId"), "targets", ["walletId"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("entryId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("walletId", sa.Integer(), nullable=False),
        sa.Column("side", sa.Enum("Compra", "Venda", name="entry_side"), nullable=False),
        sa.Column("assetType", sa.String(length=20), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("costs", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("createdAt", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["walletId"], ["wallets.walletId"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("entryId"),
    )
    op.create_index(op.f("ix_transactions_ticker"), "transactions", ["ticker"], unique=False)
    op.create_index(op.f("ix_transactions_walletId"), "transactions", ["walletId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_walletId"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_ticker"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_targets_walletId"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_snapshots_walletId"), table_name="snapshots")
    op.drop_index(op.f("ix_snapshots_date"), table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_holdings_walletId"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_ticker"), table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_wallets_userId"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
