"""wallet earnings

Revision ID: c4d1e8f2a917
Revises: 73211a401c34
Create Date: 2026-09-30 21:40:00.000000

Hand-written (autogenerate drifts on this dev DB: orphan Sep-04 tables
wallet_lots/wallet_dividends/prometheus_*/wallet_holdings emit 29 drops;
app DB user lacks CREATE DATABASE so no scaffold DB possible).
Content mirrors autogenerate style of 73211a401c34 exactly:
single create_table(earnings), zero drops.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4d1e8f2a917"
down_revision: Union[str, Sequence[str], None] = "73211a401c34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earnings",
        sa.Column("earningId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("walletId", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.Enum("Div", "JSCP", "RendTributado", name="earning_kind"), nullable=False),
        sa.Column("exDate", sa.Date(), nullable=False),
        sa.Column("payDate", sa.Date(), nullable=False),
        sa.Column("gross", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("netIrAdjusted", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.Enum("A Receber", "Recebido", name="earning_status"), nullable=False),
        sa.ForeignKeyConstraint(["walletId"], ["wallets.walletId"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("earningId"),
        sa.UniqueConstraint("walletId", "ticker", "exDate", "kind", name="uq_earnings_accrual"),
    )
    op.create_index(op.f("ix_earnings_status"), "earnings", ["status"], unique=False)
    op.create_index(op.f("ix_earnings_ticker"), "earnings", ["ticker"], unique=False)
    op.create_index(op.f("ix_earnings_walletId"), "earnings", ["walletId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_earnings_walletId"), table_name="earnings")
    op.drop_index(op.f("ix_earnings_ticker"), table_name="earnings")
    op.drop_index(op.f("ix_earnings_status"), table_name="earnings")
    op.drop_table("earnings")
    # ### end Alembic commands ###
