"""drop dead holding columns

Revision ID: d4e5f6a7b8c9
Revises: c4d1e8f2a917
Create Date: 2026-10-01 00:00:00.000000

Holding.percentIdeal (targets live in Target) + Holding.tickerName
(never populated) removed from main/models/wallet.py.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, Sequence[str], None] = "c4d1e8f2a917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holdings", "percentIdeal")
    op.drop_column("holdings", "tickerName")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("holdings", sa.Column("tickerName", sa.String(length=120), nullable=True))
    op.add_column("holdings", sa.Column("percentIdeal", sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###
